//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bntu.vsrpp.vmilyuk.lab1.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bntu.vsrpp.vmilyuk.lab1.Resources.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit and save file.
        /// </summary>
        internal static string MainWindow_Button_EditAndSave {
            get {
                return ResourceManager.GetString("MainWindow.Button.EditAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find average length.
        /// </summary>
        internal static string MainWindow_Button_FindAverageLengthOperation {
            get {
                return ResourceManager.GetString("MainWindow.Button.FindAverageLengthOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find average value.
        /// </summary>
        internal static string MainWindow_Button_FindAverageValueOperation {
            get {
                return ResourceManager.GetString("MainWindow.Button.FindAverageValueOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find max length.
        /// </summary>
        internal static string MainWindow_Button_FindMaxLengthOperation {
            get {
                return ResourceManager.GetString("MainWindow.Button.FindMaxLengthOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find max value.
        /// </summary>
        internal static string MainWindow_Button_FindMaxValueOperation {
            get {
                return ResourceManager.GetString("MainWindow.Button.FindMaxValueOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find min length.
        /// </summary>
        internal static string MainWindow_Button_FindMinLengthOperation {
            get {
                return ResourceManager.GetString("MainWindow.Button.FindMinLengthOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find min value.
        /// </summary>
        internal static string MainWindow_Button_FindMinValueOperation {
            get {
                return ResourceManager.GetString("MainWindow.Button.FindMinValueOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open file.
        /// </summary>
        internal static string MainWindow_Button_OpenFile {
            get {
                return ResourceManager.GetString("MainWindow.Button.OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read file.
        /// </summary>
        internal static string MainWindow_Button_ReadFile {
            get {
                return ResourceManager.GetString("MainWindow.Button.ReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Find average length&quot;.
        /// </summary>
        internal static string MainWindow_FindAverageLengthOperation {
            get {
                return ResourceManager.GetString("MainWindow.FindAverageLengthOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Find average value&quot;.
        /// </summary>
        internal static string MainWindow_FindAverageValueOperation {
            get {
                return ResourceManager.GetString("MainWindow.FindAverageValueOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Find max length&quot;.
        /// </summary>
        internal static string MainWindow_FindMaxLengthOperation {
            get {
                return ResourceManager.GetString("MainWindow.FindMaxLengthOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Find max value&quot;.
        /// </summary>
        internal static string MainWindow_FindMaxValueOperation {
            get {
                return ResourceManager.GetString("MainWindow.FindMaxValueOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Find min length&quot;.
        /// </summary>
        internal static string MainWindow_FindMinLengthOperation {
            get {
                return ResourceManager.GetString("MainWindow.FindMinLengthOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Find min value&quot;.
        /// </summary>
        internal static string MainWindow_FindMinValueOperation {
            get {
                return ResourceManager.GetString("MainWindow.FindMinValueOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of available operations.
        /// </summary>
        internal static string MainWindow_Label_ListAvailableOperations {
            get {
                return ResourceManager.GetString("MainWindow.Label.ListAvailableOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nodes count =.
        /// </summary>
        internal static string MainWindow_Label_NodesCount {
            get {
                return ResourceManager.GetString("MainWindow.Label.NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name: .
        /// </summary>
        internal static string MainWindow_Label_OperationName {
            get {
                return ResourceManager.GetString("MainWindow.Label.OperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result: .
        /// </summary>
        internal static string MainWindow_Label_OperatonResult {
            get {
                return ResourceManager.GetString("MainWindow.Label.OperatonResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Over numeric values.
        /// </summary>
        internal static string MainWindow_Label_OverNumericValues {
            get {
                return ResourceManager.GetString("MainWindow.Label.OverNumericValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Over strings.
        /// </summary>
        internal static string MainWindow_Label_OverStrings {
            get {
                return ResourceManager.GetString("MainWindow.Label.OverStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select an available option.
        /// </summary>
        internal static string MainWindow_Label_SelectAvailableOption {
            get {
                return ResourceManager.GetString("MainWindow.Label.SelectAvailableOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error, .
        /// </summary>
        internal static string MainWindow_MessageBox_OperationError {
            get {
                return ResourceManager.GetString("MainWindow.MessageBox.OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nodes count = .
        /// </summary>
        internal static string MainWindow_NodesCount {
            get {
                return ResourceManager.GetString("MainWindow.NodesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error. .
        /// </summary>
        internal static string MainWindow_OperationError {
            get {
                return ResourceManager.GetString("MainWindow.OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name: .
        /// </summary>
        internal static string MainWindow_OperationName {
            get {
                return ResourceManager.GetString("MainWindow.OperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result: .
        /// </summary>
        internal static string MainWindow_OperationResult {
            get {
                return ResourceManager.GetString("MainWindow.OperationResult", resourceCulture);
            }
        }
    }
}
